spring:
  application:
    name: Enviro365
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
security:
  secret: jwtSecret=======================BezKoder=Spring===========================
  expirationInMs: 86400000
securityDefinitions:
  Authorization:
    type: apiKey
    name: Authorization
    in: header
paths:
  /secured-api:
    get:
      security:
        - Authorization: []
